### PR TITLE
Fix some words and sentence in building-community.md

### PR DESCRIPTION
**Pull request by krlsdu**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by gab0gomes** [comment]
Hi, @krlsdu.

it looks like you've changed some indentations in the file... is there any specific reason for this?

**Comment by gab0gomes** [comment]
> Hi, @krlsdu.
> 
> it looks like you've changed some indentations in the file... is there any specific reason for this?

in addition, there seems to be some problem with the ellipsis on line 223.

**Comment by krlsdu** [comment]
Will look at these points!

**Comment by krlsdu** [comment]
@Gabrielr2508 both points was my mistake, I did a format clean when using the spell checker.
the commit acd0311 repair.

**Pull request merged**
