### PR TITLE
How to contribute

### PR DESCRIPTION
**Pull request by krlsdu**
- [x] Have you followed the [contributing guidelines](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md)?
- [x] Have you explained what your changes do, and why they add value to the Guides?

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**

-----

### CODE REVIEW

**Comment by gab0gomes** [comment]
Hello, @krlsdu.

I'm following up on your changes ... Congratulations on your progress. 🎊 

Not to be boring, but already being ... please keep the existing text decorations 
and when not translating a specific word put it in italics.

Thank you very much. 😄

**Comment by krlsdu** [comment]
@ Gabrielr2508 Thanks, and a suggestion, when you see some error/improvement that is in the text, create a comment on this line. That way, I do not need to look for the error / improve throughout the document.
When there is an error/improvement in N points in the document, it is ok to make a comment general. Think about!
:relaxed:

**Comment by krlsdu** [comment]
What is the reason to put in italic the word not translated?

**Comment by o-leolleo** [comment]
> What is the reason to put in italic the word not translated?

@krlsdu I think that is just to emphasize that it's a foreign word, it's a common pattern used on textbooks and other medias :)

**Comment by gab0gomes** [comment]
> @ Gabrielr2508 Thanks, and a suggestion, when you see some error/improvement that is in the text, create a comment on this line. That way, I do not need to look for the error / improve throughout the document.
> When there is an error/improvement in N points in the document, it is ok to make a comment general. Think about!

Yes, I know that. When I commented, there were many places where "open source" was written without italics. This was the main reason for the overall comment.

Sorry if you felt uncomfortable with that. :(

Thanks again. 😄

**Comment by krlsdu** [comment]
> ...
> This was the main reason for the overall comment.
> Sorry if you felt uncomfortable with that. :(
> 
> Thanks again. smile

Oh, ok!, I thought that was another issue on this \ white space [ blablabla]\
Don't worry! I'm ok with that.

**Comment by krlsdu** [comment]
About the words "open source". Some points sound better "open source" in another make more sense "código <strike>livre</strike> aberto". @Gabrielr2508 is correct :point_down: 

Can I use both or better maintain the consistency choosing one?

**Comment by gab0gomes** [comment]
> > ...
> > This was the main reason for the overall comment.
> > Sorry if you felt uncomfortable with that. :(
> > Thanks again. smile
> 
> Oh, ok!, I thought that was another issue on this \ white space [ blablabla]
> Don't worry! I'm ok with that.

I don't know. I'm using "_open source_" in everywhere. But, I think that have no problem with this. By the way, maybe "Código aberto" translates better the idea than "Código livre", and avoid confusing with "Software livre" that means something a little bit diferente.

What you think about, @leolleocomp?

**Comment by krlsdu** [comment]
> I think that is just to emphasize that it's a foreign word, it's a common pattern used on textbooks and other medias :)

@leolleocomp Good to know, but I see in other translated text neither es nor fr use this to emphasize, 

I tried in some words and I see a problem when list+bold most of cases. e.g: (Issue tracker and Pull request), the emphasis is imperceptible.

**Comment by o-leolleo** [comment]
> > > ...
> > > This was the main reason for the overall comment.
> > > Sorry if you felt uncomfortable with that. :(
> > > Thanks again. smile
> > 
> > 
> > Oh, ok!, I thought that was another issue on this \ white space [ blablabla]
> > Don't worry! I'm ok with that.
> 
> I don't know. I'm using "_open source_" in everywhere. But, I think that have no problem with this. By the way, maybe "Código aberto" translates better the idea than "Código livre", and avoid confusing with "Software livre" that means something a little bit diferente.
> 
> What you think about, @leolleocomp?

I don't see any problem on this either. I also agree with the 'Codigo Aberto' suggestion, pretty fine :)

**Comment by o-leolleo** [comment]
> > I think that is just to emphasize that it's a foreign word, it's a common pattern used on textbooks and other medias :)
> 
> @leolleocomp Good to know, but I see in other translated text neither es nor fr use this to emphasize,
> 
> I tried in some words and I see a problem when list+bold most of cases. e.g: (Issue tracker and Pull request), the emphasis is imperceptible.

Interesting. There is no strong reason behind the emphasis adoption on our case besides the one I exemplified (textbooks, etc...), I think that we've only started the translation using this as standard. Although I favor the emphasis usage just by personal taste, I would have no problem on chaging it once we agree with one standard or another. 

Also, could you explain the problem you've found out with the emphasis a bit more? I haven't got it, and I'm sorry for that.

@Gabrielr2508 could you take a look at this too?

**Comment by krlsdu** [comment]
Hi @leolleocomp, this image may be showing more about my problem.
I personally need the huge attention to note the words in italic format. (my eyes are good :smiley: )

A fun challenge!

Can you see quickly what word(s) or sentence(s) to be in italic? Write the answer on comments.

image

I know isn't a strong argument but,
I think the effort is much more than benefits. 
We will need to review the texts, paying attention in that emphasize, that other person neither will note.

**Comment by gab0gomes** [comment]
> Hi @leolleocomp, this image may be showing more about my problem.
> I personally need the huge attention to note the words in italic format. (my eyes are good 😃 )
> 
> A fun challenge!
> 
> Can you see quickly what word(s) or sentence(s) to be in italic? Write the answer on comments.
> 
> image
> 
> I know isn't a strong argument but,
> I think the effort is much more than benefits.
> We will need to review the texts, paying attention in that emphasize, that other person neither will note.

Hahaha, just as it's hard for you, it's easy for me. Maybe because of the writing and reading of scientific texts in the university ...
It's just a matter of standardization, I think. The original documents do not mention anything about it. If we decide that the translation will have an emphasis on foreign words, then we should be using it in all articles. The same thing happens if we decide not to do this. 😄

**Comment by krlsdu** [comment]
Well, can we decide about the emphasize and close this thread,  using vote like this?

> :+1: = emphasize the foreign word(s) using _italic_
> 
> :-1:  = **Not** emphasize the foreign word(s)
> 
> The time to vote starting (dd/mm/yy) at (dd/mm/yy)
> In dd/mm/yy we take the decision that __________

**Comment by gab0gomes** [comment]
Hey @MikeMcQuaid, can you help us to decide about this question of emphasis on foreign words?

**Comment by gab0gomes** [comment]
> Well, can we decide about the emphasize and close this thread, using vote like this?
> 
> > 👍 = emphasize the foreign word(s) using _italic_
> > 👎  = **Not** emphasize the foreign word(s)
> > The time to vote starting (dd/mm/yy) at (dd/mm/yy)
> > In dd/mm/yy we take the decision that __________

Sure!

**Comment by MikeMcQuaid** [comment]
@Gabrielr2508 I don't think it necessary to emphasise, personally.

**Comment by gab0gomes** [comment]
> Well, can we decide about the emphasize and close this thread, using vote like this?
> 
> > 👍 = emphasize the foreign word(s) using _italic_
> > 👎  = **Not** emphasize the foreign word(s)
> > The time to vote starting (dd/mm/yy) at (dd/mm/yy)
> > In dd/mm/yy we take the decision that __________

Hey @krlsdu and @leolleocomp we will continue without emphasizing. It will save us time.

**Comment by krlsdu** [comment]
Hi guys, I finished this file!
How to proceed now?

**Comment by gab0gomes** [comment]
> Hi guys, I finished this file!
> How to proceed now?

Just remove the wip tag, and i will merge after a basic review. :)

...and congratulations! That was a big article! Feel free to take another one! 🎉

**Comment by gab0gomes** [comment]
— @errietta, ["Why I love contributing to open source software"](https://www.errietta.me/blog/open-source/)
— @errietta, ["Porque eu amo contribuir para software open source"](https://www.errietta.me/blog/open-source/)

I have a doubt about this. Should we translate the articles title from another material? I vote no. What you think? @krlsdu @leolleocomp 

ps.: posted here because @leolleocomp could not see my comment in the code (don't know why).

**Comment by o-leolleo** [comment]
> — @errietta, ["Why I love contributing to open source software"](https://www.errietta.me/blog/open-source/)
> — @errietta, ["Porque eu amo contribuir para software open source"](https://www.errietta.me/blog/open-source/)
> 
> I have a doubt about this. Should we translate the articles title from another material? I vote no. What you think? @krlsdu @leolleocomp
> 
> ps.: posted here because @leolleocomp could not see my comment in the code (don't know why).

I favor not doing so, either.

**Comment by krlsdu** [comment]
> — @errietta, ["Why I love contributing to open source software"](https://www.errietta.me/blog/open-source/)
> — @errietta, ["Porque eu amo contribuir para software open source"](https://www.errietta.me/blog/open-source/)
> 
> I have a doubt about this. Should we translate the articles title from another material? I vote no. What you think? @krlsdu @leolleocomp
> 
> ps.: posted here because @leolleocomp could not see my comment in the code (don't know why).

I agree with you.(no translate)

**Comment by gab0gomes** [comment]
> > — @errietta, ["Why I love contributing to open source software"](https://www.errietta.me/blog/open-source/)
> > — @errietta, ["Porque eu amo contribuir para software open source"](https://www.errietta.me/blog/open-source/)
> > I have a doubt about this. Should we translate the articles title from another material? I vote no. What you think? @krlsdu @leolleocomp
> > ps.: posted here because @leolleocomp could not see my comment in the code (don't know why).
> 
> I agree with you.(no translate)

Ok, I will accept your pull request, then on revision we make the necessary changes.

**Pull request merged**
